[package]
name = "mb"
version.workspace = true
edition.workspace = true 

[dependencies]
serialport.workspace = true
thiserror.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true
