[workspace]
resolver = "2"
members = [
  "mb",
  "mb-reader",
  "mb-mock"
]
default-members = [
  "mb-reader"
]

[workspace.package]
version = "0.1.0"
edition = "2021"
author = ["erasin"]

[profile.release]
lto = "thin"

[workspace.dependencies]
serialport = "4.3.0"
thiserror = "1.0"
