[package]
name = "mb-data"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
mb = {path = "../mb"}
etcetera = "0.8"
redb = "2.1"
time = { version = "0.3", features = ["formatting", "local-offset"] }
thiserror.workspace = true
log.workspace = true
